site_name: "TGE Docs"

theme:
    name: "material"
    palette:
        scheme: slate

plugins:
    - search
    - gen-files:
          scripts:
              - scripts/gen_ref_pages.py
    - mkdocstrings:
          default_handler: python
          handlers:
              python:
                  options:
                      show_source: false
                      members_order: "source"
                      docstring_style: "google"
                  paths: [tge]
