[tool.poetry]
name = "tge"
version = "0.1.0"
description = ""
authors = ["Jayden Edara <aedara@uw.edu>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
numpy = "^1.26.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
